### ISSUE TITLE
Paper on how to implement Scigen

### ISSUE THREAD

**Issue by TomSang** [soerface/scigen-docker#3]
Is there any  introduction paper on how Scigen to work ?
Currently it can  generate computer-related  research papers. 
How to make a Scigen on other fields?

**Comment by soerface** [comment]
I don't know of any paper, but as far as I understand the sourcecode, the principle is quiet simple: The document is generated with a "start_rule", defined here as `SCIPAPER_LATEX`: https://github.com/soerface/scigen-docker/blob/2dfe4ba45e93322db1f74baf2f3181af79b42241/scigen/make-latex.pl#L112

In the rules file, `SCIPAPER_LATEX` has multiple definitions. One gets randomly chosen: https://github.com/soerface/scigen-docker/blob/2dfe4ba45e93322db1f74baf2f3181af79b42241/scigen/scirules.in#L23

This rule defines, that a `SCIPAPER_LATEX` consists of `LATEX_HEADER`, `SCI_ABSTRACT`, `SCI_INTRO` etc. Each of those is again defined one or multiple times to allow randomness. It comes down to sentences like:

> SCI_PEOPLE agree that SCI_BUZZWORD_ADJ SCI_BUZZWORD_NOUN are an interesting new topic in the field of SCI_FIELD, and SCI_PEOPLE concur

…where only single words like [SCI_PEOPLE](https://github.com/soerface/scigen-docker/blob/2dfe4ba45e93322db1f74baf2f3181af79b42241/scigen/scirules.in#L2936) are left to be replaced by a random definition.

Therefore, it should be easy to create such a grammar by switching the rules, but still a lot of work to write enough sentences and words which sound nice when pasted randomly together in this manner.

**Comment by TomSang** [comment]
Thanks!
